accounts/demo/demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include('django.contrib.auth.urls')),
]

accounts/urls.py
#
# Copyright (C) 2019 Guillaume Bernard <guillaume.bernard@koala-lms.org>
# Copyright (C) 2020 Louis Barbier <louis.barbier41@outlook.fr>
#
# This file is part of Koala LMS (Learning Management system)

# Koala LMS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# We make an extensive use of the Django framework, https://www.djangoproject.com/
from django.contrib.auth.views import PasswordResetView
from django.urls import path, include, re_path

from accounts import views
from accounts.forms import UserPasswordResetForm

app_name = 'accounts'

ajax_api_urlpatterns = [
    path('search/', views.search_user, name='ajax/search'),
    path('notification/read/<int:notification_id>', views.notification_mark_as_read, name="ajax/notification/read"),
    path('notification/delete/<int:notification_id>', views.notification_delete, name="ajax/notification/delete"),
]

urlpatterns = [
    path('', views.LoginView.as_view(), name='index'),

    path('login/', views.LoginView.as_view(), name='login'),
    path('details/', views.AccountsDetailsView.as_view(), name='details'),

    #  Password update and reset
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_reset/', PasswordResetView.as_view(form_class=UserPasswordResetForm), name="password_reset"),

    #  Account registration and activation
    path('register/', views.AccountsRegisterView.as_view(), name='register'),
    re_path(
        r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'
    ),
    re_path(
        r'send_activation_mail/(?P<uidb64_username>[0-9A-Za-z_\-]+)/$', views.resend_activation_mail,
        name='resend_email_confirmation'
    ),

    #  Ajax views
    path('ajax/', include(ajax_api_urlpatterns))
]

accounts/templates/accounts/authentication_base.html
{% extends 'accounts/base.html' %}
{% load i18n %}

{% block title %}
  {% if user.is_authenticated %}
    {% trans "Access denied" %}
  {% else %}
    {{ title }}
  {% endif %}
{% endblock %}

{% block accounts_content %}
  {# User is already authenticated, so do not show anything about authentication or registration #}
  {% if user.is_authenticated %}
    <div class="card">
      <div class="card-header">
        <h4 class="card-title mb-1 mt-1">{% trans "Access denied" %}</h4>
      </div>
      <div class="card-body">
        <div class="text-center">
          <p>
            {% blocktrans trimmed with name=user.display_name %}
              You are already logged in as <strong>{{ name }}</strong>. Thus, you <strong>cannot</strong> perform this
              operation.
            {% endblocktrans %}
          </p>
          <p>{% trans "You will be redirected in a few seconds…" %}</p>
          <script type="text/javascript">
            setTimeout(function () {
              window.location.href = "{% url 'accounts:details' %}";
            }, 5000);
          </script>
        </div>
        <hr>
        <div class="row justify-content-center">
          <a href="{% url 'accounts:details' %}" class="btn btn-outline-secondary m-1">{% trans "My details" %}</a>
        </div>
      </div>
    </div>
  {% else %}
    {% block accounts_actionblock %}{% endblock %}
  {% endif %}
{% endblock %}

accounts/templates/accounts/base.html
{% extends 'base.html' %}
{% load i18n static %}

{% block title %}{{ title }}{% endblock %}

{% block extrastyle %}{{ block.super }}
  <link rel="stylesheet" href="{% static 'accounts/style.css' %}"/>
  <script defer src="{% static 'accounts/js/notification.js' %}"></script>
  <script defer src="{% static 'accounts/fonts/fontawesome.js' %}"></script>
{% endblock %}

{% block extrahead %}
  <link rel="shortcut icon" href="{% static 'accounts/images/favicon.png' %}" type="image/x-icon">
{% endblock %}

{% block content %}
  {% include "accounts/_includes/messages.html" %}
  {% block accounts_content %}{% endblock %}
{% endblock %}

accounts/templates/accounts/details.html
{% extends 'accounts/base.html' %}
{% load i18n %}

{% block accounts_content %}
  <div class="card">
    <div class="card-header">
      <h4 class="card-title mb-1 mt-1">{% trans "Personal information" %}</h4>
    </div>
    <div class="card-body">
      <form method="post">
        {% csrf_token %}
        <div class="form-row">
          <div class="col-md-6">
            {% include "accounts/_includes/basic_block.html" with field=form.first_name %}
          </div>
          <div class="col-md-6">
            {% include "accounts/_includes/basic_block.html" with field=form.last_name %}
          </div>
        </div>
        {% include "accounts/_includes/basic_block.html" with field=form.email icon="fa-at" %}
        {% include "accounts/_includes/basic_block.html" with field=form.preferred_language icon="fa-flag" %}
        <button type="submit" class="btn btn-primary float-right">
          {% trans "Update personnal information" %}
        </button>
      </form>
    </div>
  </div>

  <div class="card mt-3">
    <div class="card-header">
      <a href="{% url 'accounts:password_change' %}" class="float-right btn btn-outline-primary">
        {% trans "Change password" %}
      </a>
      <h4 class="card-title mb-1 mt-1">{% trans "Password" %}</h4>
    </div>
  </div>

  <div class="card mt-3">
    <div class="card-header">
      <h4 class="card-title mb-1 mt-1">{% trans "Groups" %}</h4>
    </div>
    <div class="card-body">
      {% if user.groups.count > 0 %}
        {% blocktrans with groups=user.groups.all|join:', ' count nb=user.groups.count %}
          You are registered in the group: <i>{{ groups }}</i>.
        {% plural %}
          You are registered in the groups: <i>{{ groups }}</i>.
        {% endblocktrans %}
      {% else %}
        {% trans "You are not registered in any group yet." %}
      {% endif %}
    </div>
  </div>

{% endblock %}

accounts/templates/accounts/dropdown.html
{% load i18n static %}

<!-- Notifications -->
{% if user.is_authenticated %}
  <script defer src="{% static 'accounts/js/notification.js' %}"></script>
  <li class="nav-item dropdown">
    <a class="nav-link" href="#" id="notifications_dropdown_link" data-toggle="dropdown"
       aria-haspopup="true" aria-expanded="false">
      <i class="fa fa-bell"></i>
      {% if user.unread_notifications.count > 0 %}
        <span class="badge badge-danger align-middle" id="notification_counter">
        {{ user.unread_notifications.count }}
      </span>
      {% endif %}
    </a>
    {% if user.notifications.count > 0 %}
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="notifications_dropdown_link"
           id="notifications_dropdown">
        {% for notification in user.notifications.all %}

          {% if forloop.counter0 != 0 %}
            <div class="dropdown-divider" id="notification_divider_{{ notification.id }}"></div>
          {% endif %}

          <div class="px-3" id="notification_{{ notification.id }}">

            {# The notification content and buttons to mark as read or delete #}
            <div class="row" style="min-width: 25rem !important;">

              {# Notification message #}
              <div class="col-10 pr-0">
                <p class="small {% if notification.is_read %}text-muted{% endif %} text-justify"
                   id="notification_{{ notification.id }}_message">
                  {{ notification.message }}
                </p>
              </div>

              {# Buttons to mark the notification as read or to delete it #}
              <div class="btn-group-vertical col-auto pr-0">
                {% csrf_token %}
                {% if not notification.is_read %}
                  <a onclick="notification_mark_as_read({{ notification.id }})" class="btn btn-sm"
                     id="notification_{{ notification.id }}_mark_as_read_btn">
                    <i class="fa fa-eye-slash"></i>
                  </a>
                {% endif %}
                <a onclick="notification_delete({{ notification.id }})" class="btn btn-sm"
                   id="notification_{{ notification.id }}_delete_btn">
                  <i class="fa fa-times"></i>
                </a>
              </div>
            </div>

            {# The notification timestamp and target link #}
            <div class="clearfix">
              <span class="small float-left"><i class="fa fa-clock pr-1"></i> {{ notification.timestamp | date }}</span>
              {% if notification.target %}
                <a class="small float-right" href="{{ notification.target }}"
                   data-toggle="tooltip" data-placement="left"
                   title="{% blocktrans with url=notification.target %}Go to {{ url }}{% endblocktrans %}">
                  <i class="fa fa-link pr-1"></i>{% trans "Access item" %}
                </a>
              {% endif %}
            </div>

          </div>
        {% endfor %}
      </div>
    {% endif %}
  </li>
{% endif %}
<!-- End of notifications -->

<!-- User account -->
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="accounts_dropdown" data-toggle="dropdown"
     aria-haspopup="true" aria-expanded="false">
    {% if user.is_authenticated %}
      {{ user.display_name }}
    {% else %}
      {% trans "Log in" %}
    {% endif %}
  </a>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="accounts_dropdown">
    {% if user.is_authenticated %}
      <a class="dropdown-item"
         href="{% url 'accounts:details' %}">{% trans "My details" %}</a>
      <a class="dropdown-item" href="{% url 'logout' %}">{% trans "Log out" %}</a>
    {% else %}
      <a class="dropdown-item" href="{% url 'accounts:login' %}">{% trans "Log in" %}</a>
      <a class="dropdown-item"
         href="{% url 'accounts:register' %}">{% trans "Create a new account" %}</a>
    {% endif %}
  </div>
</li>
<!-- End of user account -->

accounts/templates/accounts/register.html
{% extends 'accounts/authentication_base.html' %}
{% load i18n %}

{% block accounts_actionblock %}
  <div class="card">
    <div class="card-header">
      <a href="{% url 'accounts:login' %}" class="float-right btn btn-outline-primary">{% trans "Sign in" %}</a>
      <h4 class="card-title mb-1 mt-1">{% trans "Create a new account" %}</h4>
    </div>
    <div class="card-body">
      <form method="post">
        {% csrf_token %}

        <h5>{% trans "About you…" %}</h5>
        <div class="form-row">
          <div class="col-md-6">
            {% include "accounts/_includes/basic_block.html" with field=form.first_name %}
          </div>
          <div class="col-md-6">
            {% include "accounts/_includes/basic_block.html" with field=form.last_name %}
          </div>
        </div>

        <h5>{% trans "Your credential information…" %}</h5>
        {% include "accounts/_includes/basic_block.html" with field=form.username icon="fa-user" %}
        {% include "accounts/_includes/basic_block.html" with field=form.email icon="fa-at" %}

        <div class="form-row">
          <div class="col-md-6">
            {% include "accounts/_includes/password_block.html" with password=form.password1 %}
          </div>
          <div class="col-md-6">
            {% include "accounts/_includes/password_block.html" with password=form.password2 %}
          </div>
        </div>

        <button type="submit" class="btn btn-primary float-right">{% trans "Create the new account" %}</button>
      </form>
    </div>
  </div>
{% endblock %}