accounts/demo/demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include('django.contrib.auth.urls')),
]

accounts/urls.py
#
# Copyright (C) 2019 Guillaume Bernard <guillaume.bernard@koala-lms.org>
# Copyright (C) 2020 Louis Barbier <louis.barbier41@outlook.fr>
#
# This file is part of Koala LMS (Learning Management system)

# Koala LMS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# We make an extensive use of the Django framework, https://www.djangoproject.com/
from django.contrib.auth.views import PasswordResetView
from django.urls import path, include, re_path

from accounts import views
from accounts.forms import UserPasswordResetForm

app_name = 'accounts'

ajax_api_urlpatterns = [
    path('search/', views.search_user, name='ajax/search'),
    path('notification/read/<int:notification_id>', views.notification_mark_as_read, name="ajax/notification/read"),
    path('notification/delete/<int:notification_id>', views.notification_delete, name="ajax/notification/delete"),
]

urlpatterns = [
    path('', views.LoginView.as_view(), name='index'),

    path('login/', views.LoginView.as_view(), name='login'),
    path('details/', views.AccountsDetailsView.as_view(), name='details'),

    #  Password update and reset
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_reset/', PasswordResetView.as_view(form_class=UserPasswordResetForm), name="password_reset"),

    #  Account registration and activation
    path('register/', views.AccountsRegisterView.as_view(), name='register'),
    re_path(
        r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'
    ),
    re_path(
        r'send_activation_mail/(?P<uidb64_username>[0-9A-Za-z_\-]+)/$', views.resend_activation_mail,
        name='resend_email_confirmation'
    ),

    #  Ajax views
    path('ajax/', include(ajax_api_urlpatterns))
]

accounts/templates/base.html
{% load i18n static %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% trans "Koala" %}{% endblock %}</title>

  {% block extrastyle %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
  {% endblock %}

  {% block extrahead %} {% endblock %}
</head>

<header>
  <nav class="navbar navbar-expand-lg navbar-expand-md navbar-dark bg-dark">
    <a class="navbar-brand text-light" href="{% url 'accounts:index' %}">{% trans "Accounts" %}</a>
    <ul class="navbar-nav ml-auto mt-lg-0">
      <li class="nav-item">
        {% include 'accounts/dropdown.html' %}
      </li>
    </ul>
  </nav>
</header>
<body>

{% block content %}
  <div class="container-fluid">
    <div class="row mt-3 mb-3">
      <div class="col-12 col-sm-12 offset-md-1 col-md-10 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        {% include "accounts/_includes/messages.html" %}
        {% block accounts_content %}{% endblock %}
      </div>
    </div>
  </div>
{% endblock %}
</body>
</html>